### ISSUE TITLE
How to migrate from tbc to wotlk on CLI

### ISSUE THREAD

**Issue by LordFckHelmchen** [layday/instawow#116]
Dear @layday,

thanks for the great tool! I'm currently transitioning my tbc installation to wotlk and wanted to know how one would do this. Is there an upgrade option to change (not switch) the profile of an existing installation?

Thanks for any hints!

**Comment by layday** [comment]
It is done automatically when you upgrade to the latest version of instawow (v1.44.0).

**Comment by LordFckHelmchen** [comment]
Okay thanks for the hint - maybe add a short section in the README on migrating versions (can do it if you want). 

For my installation, a lot of addons where not found anymore after the update (addons like TitanBar...). If you have some ideas of how to debug that, I can do some investigation...

**Comment by layday** [comment]
They are not found because they don't have WotLK releases. I wasn't sure if it would be appropriate to install TBC add-ons in the WotLK client as a stopgap for the first (say) couple of months. Add-on authors (read: @AcidWeb :) have said that TBC add-ons might be incompatible so I've ended up erring on the side of caution.

> Okay thanks for the hint - maybe add a short section in the README on migrating versions (can do it if you want).

Sure!

**Comment by layday** [comment]
Migration note added in https://github.com/layday/instawow/commit/fc73f7ec893d765de57151f666a2662d44f5a981.
