### ISSUE TITLE
Github: no files found 

### ISSUE THREAD

**Issue by choelzl** [layday/instawow#153]
Repo: https://github.com/curseforge-mirror/omnicd
It has releases for classic and retail. 

> instawow install https://github.com/curseforge-mirror/omnicd
> ✗ github:curseforge-mirror/omnicd
>   no files found for: any_flavour=None; any_release_type=None;
>     version_eq=None

**Comment by layday** [comment]
It's because none of the releases carry [add-on-specific metadata](https://github.com/ogri-la/release.json-specification) and instawow falls back on extracting the add-on metadata from the zip file, attempting to _case-sensitively_ match the add-on folder name ("OmniCD") against the zip name ("omnicd-v11.0.2.2807.zip").  I suppose we could ignore casing, but this hasn't cropped up till now 'cause having the same casing is the norm.

**Comment by layday** [comment]
What this org/repo's doing is honestly pretty far out: tri-hourly duplicate releases of add-ons which have explicitly opted out third-party distribution, without standardised metadata, tags which do not reflect the version number, and filenames which are lowercased, contrary to convention.  If you'd like to install 'restricted' add-ons from CF, there's better ways than this.  You'll find clues of what those might be interspersed in the [source code](https://github.com/layday/instawow/blob/main/src/instawow/_sources/cfcore.py).
