### ISSUE TITLE
Proposal: UI Client

### ISSUE THREAD

**Issue by cwilby** [layday/instawow#35]
👋 

Recently learned about this project and was thinking about creating a UI on top of the console application.

A visual prototype can be found here: https://github.com/cwilby/instawow-ui

**Comment by cwilby** [comment]
Fun idea, but second take - this project is great because it's lightweight from the command line.  Adding a UI kind of defeats the purpose.

**Comment by layday** [comment]
First off, thanks for your interest in instawow - it’s amazing to see other people be inspired by my work, that they’d want to build a GUI around it!

I see you changed your mind, but for a bit of history: this is something I had considered early on in instawow's development and there was WebSocket API for exactly this purpose - an Electron GUI.  It never really came to be for lack of time and, uh, know-how and I dropped the API in layday/instawow@84d04c76669124cec43d5f62187e08d300524de4.  Electron appealed to me because of how malleable it appears to be in comparison to conventional GUI frameworks like Qt; though the complexity around IPC and packaging and distribution had the opposite effect.  There are a number of [other GUIs](https://ogri-la.github.io/wow-addon-managers/?preset/name=default&field/maintained=yes&field/classic=yes&field/ui=GUI) that have surfaced since my own ill-fated attempt - notably [strongbox](https://github.com/ogri-la/strongbox), which is the one I'd recommend to non-crustaceans.

**Comment by cwilby** [comment]
Very interesting, thank you for sharing your insights - it's good to know there could have been an interface to integrate with! 

I'll be sticking with instawow - and this has been a fun re-exploration of Electron.  It's still really heavy compared to native alternatives.

**Comment by layday** [comment]
In case you are interested, I have.... reversed course and have been working on a GUI the past few days, a prototype of which you can find [here](https://github.com/layday/instawow/tree/feature-oh-my-gui/gui).

<img width="912" alt="v0 1 0" src="https://user-images.githubusercontent.com/31134424/91232954-e4247200-e738-11ea-9712-7c7768fc771a.png">

**Comment by eVen-gits** [comment]
Hello!

I dont want to necropost here, but how is this launched? I've installed the package through `pipx`, but using `-h` flag doesnt show any info about that and I wasn't able to find any relevnat information about it either (except screenshots).

Thanks for pointing me in the right dirrection!

**Comment by layday** [comment]
You're only able to install the CLI with pip(x).  The GUI is available from [GitHub releases](https://github.com/layday/instawow/releases/latest).
