### ISSUE TITLE
Sync Weakauras using a Wago account

### ISSUE THREAD

**Issue by qelix** [layday/instawow#53]
First of all, thanks a lot for the project! I was looking for a decent AddOn helper that works on Linux and was very glad to discover this one. What really got me hooked at the end of the day was the Weakauras updater, such a neat idea to include it.

However, it was a little frustrating to get it to work. First of all, it'd be nice if you specified that by `account` you mean your WoW account (or the one in the WTF folder to be more precise) instead of your Wago account. It took me a while to figure that out and only got the hint by reading the help section of the official Weakauras Companion. I guess you're not to blame because you just replicated the way the official companion works but damn, it's pretty counter intuitive!

Wouldn't a sync using a Wago account be much nicer? The account allows you to star Weakauras and even entire collections (such as [this one](https://wago.io/BkOj_-RBQ)), and using their API I suppose that you could easily download them instead of looking for already imported WAs in the saved vars.  I feel like that's a little more intuitive than the current approach and lets you add more WAs much quicker.

**Comment by layday** [comment]
I'm not particularly convinced of the usefulness of the 'account' setting.  I've half a mind to remove it and combine WAs from all accounts on update.  You are right that it's confusing - at the very least I should clarify that it's meant to be your WoW account in the README.  I'm not fond of the whole saved vars thing, either.  The saved vars parser is written in pure Python, it supports a subset of Lua table syntax and it's slow.  It's also very unlike how add-ons are managed in *instawow* - a better option might be to extend reconciliation to WA and Plater and handle installed WAs and Plateroos in a similar fashion to add-ons. I need to mull this one over.

As for providing features which aren't available in the WA desktop app, that would require the cooperation of the Wago and WA devs.  For syncing in particular, I would posit that the majority of Wago users do not have a Wago account or do not log into their account.  *instawow* would still need to know whether a starred aura is installed because the WeakAuras Companion add-on places new auras in a 'stash' for the player to install when they log into WoW - updated WAs get thrown in a separate array - so we'd have to figure out a way to keep track of them indepedently of saved vars.

**Comment by qelix** [comment]
> For syncing in particular, I would posit that the majority of Wago users do not have a Wago account or do not log into their account.
 
Fair enough. It also doesn't seem like a good idea to force users to make yet another account or abuse systems that Wago implemented with a different purpose in mind. 

> instawow would still need to know whether a starred aura is installed because the WeakAuras Companion add-on places new auras in a 'stash' for the player to install when they log into WoW [...]

How can you add new auras at all? I thought that the only way of adding them is through manually importing strings in-game.

> a better option might be to extend reconciliation to WA and Plater and handle installed WAs and Plateroos in a similar fashion to add-ons. I need to mull this one over.

I like this a lot - what do you think of going even further and allowing the user to _install_ new auras and collections (and Plateroos) just like they would install an addon? This means that WAs are basically just another addon, unifying the whole API and hopefully a little of the codebase. Maybe you could simply add another host that specifically handles Wago stuff and functions kind of like a proxy. To the user and your CLI, a WA appears to be an addon, while the host bridges the gap and makes sure it's installed accordingly. Then again, I haven't checked how all of this is implemented and if it would work; this is just off the top of my head.

This probably still suffers from the new-vs-updated-auras problem which I haven't really understood properly. 


Really, what bothers me the most with Wago is how they expect you to install their auras. I don't want to copy-paste 20 different strings directly into my game client just to install a collection of WAs. Any solution that fixes this would be much appreciated :)

**Comment by layday** [comment]
> How can you add new auras at all? I thought that the only way of adding them is through manually importing strings in-game.

There was a [plan](https://github.com/WeakAuras/WeakAuras-Companion/issues/44) to push WAs from Wago to the Companion app.  The Companion app would write them to the Companion add-on and the WA configuration panel would have been modified in some manner to offer WAs from the Companion add-on for installation.  If you were logged in, you'd have been forced to reload your UI before the new auras would be visible to WA.  I recall being able to send WAs from Wago to the Companion app but they must've removed the option at some point - which is really no surprise considering how convoluted this all turned out to be.  So, there doesn't seem to be any other way to install WAs other than copying and pasting indecipherable strings still.

**Comment by qelix** [comment]
I see, it apparently still works if you set `enableCompanion` to `true` in your JavaScript console, which is at least a step forward. 

As for treating WAs as addons - are you okay with the idea or do you consider it out of scope for the project? I'd try giving it a shot in a PR. Unless, of course, you outright say that you wouldn't want to see this merged anyway.

**Comment by layday** [comment]
I would welcome unifying add-ons and WAs but it's probably going to be quite complex.

**Comment by layday** [comment]
I've made some improvements to the WeakAuras updater in the latest version:

* I've removed the `account` option.  The updater will combine auras from all accounts if you happen to use multiple of them.
* I've added the auto-update variant to the catalogue.  It will appear in search results and will be available for reconciliation.  It is also installable from the GUI.
* Saved variables will not be re-parsed unless the file has been modiifed.  This should shave a few of seconds off rebuilding the add-on.

**Comment by qelix** [comment]
Thanks a lot, looking good! 

As you'll probably have guessed by now, I've been too lazy to look into merging add-ons and WAs. I'll open a new issue if I decide to try it some day in the future.

As for the other concerns, I think you've done all that can be done without unreasonable effort - at the end of the day the feature set is on par with the official WeakAuras Companion and the way it works now is pretty intuitive. I'd consider the issue closed, thank you for your time!
