### ISSUE TITLE
Some memory leak in windows gui

### ISSUE THREAD

**Issue by lacerated** [layday/instawow#82]
![image](https://user-images.githubusercontent.com/32882699/124316717-b42ad400-db7e-11eb-9d09-62ba2d9f9536.png)
For a simple app it uses more memory than chrome and firefox combined.

**Comment by layday** [comment]
ugh, does it rack up over time, or does it use up a lot of memory from the start?

**Comment by layday** [comment]
I can repro it in a Windows VM but unfortunately that's far too slow to get any serious debugging done.  I assume it has something to do with how we drive the Chromium Embedded Framework (CEF); but rather than waste time trying to figure out whatever's going on with CEF, the more sensible option would be to use WebView2 instead.  But again, I'd need to have something more performant to work with than a Windows VM running on Qemu on a Mac laptop...

**Comment by lacerated** [comment]
> 
> 
> ugh, does it rack up over time, or does it use up a lot of memory from the start?

it starts with around 150-200Mb  and grows over time

**Comment by layday** [comment]
Would appreciate any assistance with making the switch to Webview2, I don't currently have the capacity to work on it.

**Comment by layday** [comment]
Well, now that I've switched to WebView2, I can see that my suspicion was incorrect.  This is a bug in our GUI toolkit (or rather, an old version of the .NET wrapper library that they use). Tracked at https://github.com/beeware/toga/issues/1108.  Hopefully, a new version will be released soon.

**Comment by layday** [comment]
Fixed in v1.35.0.
